name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # el escaneo de códigos de barras
  qr_code_scanner: ^0.7.0
  permission_handler: ^10.3.0

  # Agregamos MongoDB Realm para base de datos
  flutter_mongodb_realm: ^2.3.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets utilizados en la aplicación
  assets:
    - assets/LOGOBUKZ1.png
